<?php

namespace intrepion\PhoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactInfoRepository extends EntityRepository
{
}
