parameters:
#    intrepion_phone.example.class: intrepion\PhoneBundle\Example

services:
#    intrepion_phone.example:
#        class: %intrepion_phone.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
